"""Jinja2 templates and rendering helpers for emails and GitHub issues."""

from __future__ import annotations

import datetime as dt
from typing import Any, Dict

from jinja2 import Environment, BaseLoader, Template


_ENV = Environment(loader=BaseLoader(), autoescape=False, trim_blocks=True, lstrip_blocks=True)


EMAIL_TEMPLATE_FR = _ENV.from_string(
    """Objet: Candidature stage PFE – {{ project.title }} ({{ project.company or 'Entreprise' }})

Bonjour,

Je me permets de vous contacter au sujet de l'opportunité de stage PFE intitulée
"{{ project.title }}" chez {{ project.company or 'votre entreprise' }}.

Je suis actuellement étudiant(e) en dernière année et je m'intéresse particulièrement
à ce sujet, qui correspond bien à mon profil et à mes compétences.

Quelques informations:
- Projet: {{ project.title }}
- Entreprise: {{ project.company or 'N/A' }}
- Lien / Source: {{ project.link or project.source_url }}
- Fitness (depuis le fichier CSV): {{ project.fitness or 'N/A' }} {% if project.fitness_match_approx %}(approximation, à vérifier){% endif %}

Vous trouverez ci-joint mon CV pour plus de détails sur mon parcours.

{{ my_name or '{MY_NAME}' }}
Email: {{ my_email or '{MY_EMAIL}' }}
Téléphone: {{ my_phone or '{MY_PHONE}' }}

--
Note: cette candidature a été préparée automatiquement par mon bot "PFE Aggregator".
Merci de vérifier manuellement les informations avant envoi.
"""
)


EMAIL_TEMPLATE_EN = _ENV.from_string(
    """Subject: PFE Internship Application – {{ project.title }} ({{ project.company or 'Company' }})

Hello,

I am reaching out regarding the PFE internship opportunity titled
"{{ project.title }}" at {{ project.company or 'your company' }}.

I am currently a final-year student and I am very interested in this topic,
which seems well aligned with my skills and background.

Some details:
- Project: {{ project.title }}
- Company: {{ project.company or 'N/A' }}
- Link / Source: {{ project.link or project.source_url }}
- Fitness (from CSV): {{ project.fitness or 'N/A' }} {% if project.fitness_match_approx %}(approximate match, please double-check){% endif %}

Please find my CV attached for more information.

{{ my_name or '{MY_NAME}' }}
Email: {{ my_email or '{MY_EMAIL}' }}
Phone: {{ my_phone or '{MY_PHONE}' }}

--
Note: this draft was prepared automatically by my "PFE Aggregator" bot.
Please review and edit before sending.
"""
)


ISSUE_TEMPLATE = _ENV.from_string(
    """## PFE Opportunity

- **Title:** {{ project.title }}
- **Company:** {{ project.company or 'N/A' }}
- **Link:** {{ project.link or project.source_url }}
- **Fitness:** {{ project.fitness or 'N/A' }} {% if project.fitness_match_approx %}(approximate company match; verify){% endif %}
- **Date scraped:** {{ project.date_scraped }}

### Description

{{ project.description or 'No description extracted.' }}

---

_Generated by PFE Aggregator bot on {{ today }}._
"""
)


def render_email(project: Dict[str, Any], my_info: Dict[str, str], language: str = "fr") -> str:
    """Render an email body for a project.

    language: "fr" or "en".
    """

    tpl: Template
    if language.lower().startswith("en"):
        tpl = EMAIL_TEMPLATE_EN
    else:
        tpl = EMAIL_TEMPLATE_FR

    return tpl.render(project=project, **my_info)


def render_issue(project: Dict[str, Any]) -> str:
    return ISSUE_TEMPLATE.render(project=project, today=dt.date.today().isoformat())


__all__ = ["render_email", "render_issue"]

